/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class T_Principal extends javax.swing.JFrame {

    /**
     * Creates new form T_Principal
     */
    public T_Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmcadastrar = new javax.swing.JMenu();
        jmicliente = new javax.swing.JMenuItem();
        jmiproduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmisair = new javax.swing.JMenuItem();
        jmpesquisar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);

        jmcadastrar.setMnemonic('c');
        jmcadastrar.setText("Cadastrar");
        jmcadastrar.setToolTipText("Cadastrar");
        jmcadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmicliente.setMnemonic('c');
        jmicliente.setText("Cliente");
        jmicliente.setToolTipText("Cliente");
        jmcadastrar.add(jmicliente);

        jmiproduto.setMnemonic('p');
        jmiproduto.setText("Produto");
        jmiproduto.setToolTipText("Produto");
        jmiproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiprodutoActionPerformed(evt);
            }
        });
        jmcadastrar.add(jmiproduto);
        jmcadastrar.add(jSeparator1);

        jmisair.setMnemonic('s');
        jmisair.setText("Sair");
        jmisair.setToolTipText("Sair");
        jmisair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmisairActionPerformed(evt);
            }
        });
        jmcadastrar.add(jmisair);

        jMenuBar1.add(jmcadastrar);

        jmpesquisar.setMnemonic('p');
        jmpesquisar.setText("Pesquisar");
        jmpesquisar.setToolTipText("Pesquisar");
        jmpesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jmpesquisar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiprodutoActionPerformed

    private void jmisairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmisairActionPerformed
        int recebe = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair da Aplicação", JOptionPane.YES_NO_OPTION);
        if(recebe == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jmisairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmcadastrar;
    private javax.swing.JMenuItem jmicliente;
    private javax.swing.JMenuItem jmiproduto;
    private javax.swing.JMenuItem jmisair;
    private javax.swing.JMenu jmpesquisar;
    // End of variables declaration//GEN-END:variables
}
